p2p-port=50303
rpc-http-port=38555
rpc-http-api=["NET","ETH","WEB3","ADMIN","TXPOOL","QBFT"]
host-allowlist=["*"]
rpc-http-enabled=true 
rpc-ws-enabled=true
rpc-ws-port=38565
tx-pool="sequenced"
data-storage-format="FOREST"
data-path="./data"
tx-pool-no-local-priority=true
min-gas-price=0
tx-pool-limit-by-account-percentage=0.15
rpc-http-max-active-connections=2000
rpc-ws-max-active-connections=2000
metrics-enabled=true
metrics-port=39551
Xsnapsync-server-enabled=true
